TOP_ASM = index.asm
DEPS = main.asm minirogue-c64-charset.asm minirogue-c64-colors.asm minirogue-c64-map.asm ../common/cia1_regs.asm ../common/cia2_regs.asm ../common/vic_regs.asm

PRG = charset.prg

include ../common/CommonC64.make
