TOP_ASM = index.asm
DEPS = main.asm minirogue-c64-charset.asm minirogue-c64-colors.asm minirogue-c64-map.asm ../common/vic_regs.asm ../common/cia1_regs.asm ../common/cia2_regs.asm ../common/common.asm blit_viewport.asm defs.asm menu-charset.asm menu-colors.asm menu-map.asm viewport_globals.asm

PRG = screen_splitting.prg

include ../common/CommonC64.make
